# Home Assistant Package for ESP32 Device
# Place this file in: config/packages/esp32_device.yaml
# Make sure packages are enabled in configuration.yaml:
# homeassistant:
#   packages: !include_dir_named packages

mqtt:
  sensor:
    # JSON sensors - extracting values from single JSON topic
    - name: "ESP32 Temperature"
      state_topic: "esp32/sensors"
      unit_of_measurement: "°F"
      device_class: temperature
      value_template: "{{ value_json.temperature }}"
      icon: mdi:thermometer
      
    - name: "ESP32 Humidity"
      state_topic: "esp32/sensors"
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ value_json.humidity }}"
      icon: mdi:water-percent
      
    - name: "ESP32 WiFi Signal"
      state_topic: "esp32/sensors"
      unit_of_measurement: "dBm"
      device_class: signal_strength
      value_template: "{{ value_json.rssi }}"
      icon: mdi:wifi
      
    - name: "ESP32 Uptime"
      state_topic: "esp32/sensors"
      unit_of_measurement: "s"
      value_template: "{{ value_json.uptime }}"
      icon: mdi:timer-outline
      
  binary_sensor:
    - name: "ESP32 Connected"
      state_topic: "esp32/status"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity
      
  switch:
    - name: "ESP32 OTA Update"
      state_topic: "esp32/ota/state"
      command_topic: "beacon"
      payload_on: "UPDATE"
      payload_off: "IDLE"
      state_on: "updating"
      state_off: "ready"
      icon: mdi:upload

# Input text for custom messages to ESP32
input_text:
  esp32_message:
    name: ESP32 Custom Message
    initial: ""
    max: 100

# Automation to send custom messages
automation:
  - id: esp32_send_message
    alias: "ESP32 - Send Custom Message"
    trigger:
      - platform: state
        entity_id: input_text.esp32_message
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state | length > 0 }}"
    action:
      - service: mqtt.publish
        data:
          topic: "beacon"
          payload: "{{ states('input_text.esp32_message') }}"
      - service: input_text.set_value
        target:
          entity_id: input_text.esp32_message
        data:
          value: ""

  - id: esp32_ota_trigger
    alias: "ESP32 - Trigger OTA Update"
    trigger:
      - platform: state
        entity_id: switch.esp32_ota_update
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "beacon"
          payload: "OTA_UPDATE"
      - delay:
          seconds: 2
      - service: switch.turn_off
        target:
          entity_id: switch.esp32_ota_update

# Dashboard Card Configuration (Lovelace)
# Copy this to your dashboard:
#
# type: vertical-stack
# cards:
#   - type: entities
#     title: ESP32 Device Control
#     entities:
#       - entity: binary_sensor.esp32_connected
#         name: Connection Status
#       - entity: sensor.esp32_temperature
#         name: Temperature
#       - entity: switch.esp32_ota_update
#         name: Trigger OTA Update
#       - entity: input_text.esp32_message
#         name: Send Message
#   - type: history-graph
#     title: Temperature History
#     entities:
#       - entity: sensor.esp32_temperature
#     hours_to_show: 24
#     refresh_interval: 0
